version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8081:80"
    env_file: [".env"]
    volumes:
      - ./src:/var/www/html   # pratique en dev
    depends_on: [db]

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cvdb
      MYSQL_USER: cvuser
      MYSQL_PASSWORD: cvpass
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
